In [1]:
import numpy as np

### Write a function so that the columns of the output matrix are powers of the input vector.

### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

### HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

https://numpy.org/doc/stable/reference/generated/numpy.vander.html

In [2]:
#x = np.arange(1,10,k=0)
#np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
#np.column_stack([x**(N-1-i) for i in range(N)])
N = 3
for i in range(N): print(N-i-1)

2
1
0


In [3]:
x = np.array([1,2,3,4])

In [4]:
np.vander(x)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [5]:
np.vander(x, increasing = True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [6]:
N= 3

In [7]:
np.vander(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [8]:
np.vander(x,N, increasing = True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

In [9]:
np.column_stack([x**(N-i-1) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [10]:
''' Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


'''

' Problem Statement 2:\nGiven a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of\nthe given sequence is defined as follows:\nThe moving average sequence has n-k+1 elements as shown below.\nThe moving averages with k=4 of a ten-value sequence (n=10) is shown below\ni 1 2 3 4 5 6 7 8 9 10\n===== == == == == == == == == == ==\nInput 10 20 30 40 50 60 70 80 90 100\ny1 25 = (10+20+30+40)/4\ny2 35 = (20+30+40+50)/4\ny3 45 = (30+40+50+60)/4\ny4 55 = (40+50+60+70)/4\ny5 65 = (50+60+70+80)/4\ny6 75 = (60+70+80+90)/4\ny7 85 = (70+80+90+100)/4\nThus, the moving average sequence has n-k+1=10-4+1=7 values.\n\nQuestion: Write a function to find moving average in an array over a window:\nTest it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.\n\n\n'

In [11]:
import numpy as np
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81,99, 100, 150])

In [13]:
print(sum(x[0:3]),'\n',sum(x[1:4]),'\n',sum(x[2:5]),'\n',sum(x[3:6]),'\n',sum(x[4:7]),'\n',sum(x[5:8]),'\n',sum(x[6:9]),'\n',sum(x[7:10]),'\n')

15 
 14 
 17 
 20 
 29 
 86 
 148 
 218 



In [26]:
r = []
for k in range(2,13):
    b=3
    for i in x :
        if b <=3:
            print(   round(sum(x[k-2:k+1]) /3,2)  )
            r.append(sum(x[k-2:k+1]))
            b += 1

5.0
4.67
5.67
6.67
9.67
28.67
49.33
72.67
84.0
93.33
116.33


In [27]:
r

[15, 14, 17, 20, 29, 86, 148, 218, 252, 280, 349]